### ISSUE TITLE
Look into LDF for Wikidata

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Daniel-Mietchen/ideas#394]
as per
https://www.wikidata.org/wiki/Wikidata:Linked_Data_Fragments
and
https://ldfclient.wmflabs.org
and
https://query.wikidata.org/bigdata/ldf
and
https://github.com/SuLab/GeneWikiCentral/issues/53

**Comment by Daniel-Mietchen** [comment]
Here is a query for all P932 statements (the second includes a loop over the results pages of the first):
- https://query.wikidata.org/bigdata/ldf?subject=&predicate=http%3A%2F%2Fwww.wikidata.org%2Fprop%2Fstatement%2FP932&object= .
- https://ldfclient.wmflabs.org/#query=SELECT%20%3Fitem%20%3FPMCID%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP932%20%3FPMCID%0A%7D

**Comment by Daniel-Mietchen** [comment]
looping syntax: 
https://query.wikidata.org/bigdata/ldf?predicate=http%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2FP932&page=1153

**Comment by Daniel-Mietchen** [comment]
See also https://github.com/LinkedDataFragments/Server.js .

**Comment by Daniel-Mietchen** [comment]
currently running
```bash
for pages in {1..40000}; do echo "Page ${pages}\n" curl https://query.wikidata.org/bigdata/ldf?predicate=http%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2FP932&page=${pages} ; sleep 0.2 ; done  > P932-downloads.txt 
```

**Comment by Daniel-Mietchen** [comment]
A [useful query](https://ldfclient.wmflabs.org/#query=SELECT%20DISTINCT%20%3Fwork%20%0AWHERE%20%7B%20%0A%20%20%20%20%3Fstatement%20prov%3AwasDerivedFrom%2Fpr%3AP248%20%3Fwork%20.%0A%20%20%20%20%3Fwork%20wdt%3AP2860%20%3Fcites%20.%0A%20%20%20%20%3Fciting%20wdt%3AP2860%20%3Fwork%20.%0A%7D%0ALIMIT%20100%0A) that runs nicely under LDF:

```SPARQL
SELECT DISTINCT ?work 
WHERE { 
    ?statement prov:wasDerivedFrom/pr:P248 ?work .
    ?work wdt:P2860 ?cites .
    ?citing wdt:P2860 ?work .
}
LIMIT 100

```

**Comment by Daniel-Mietchen** [comment]
In order to download results from the LDF endpoint, I was [told](https://twitter.com/RubenVerborgh/status/981053093893869568) to use a query client, e.g. [Node's ldf-client](https://www.npmjs.com/package/ldf-client).

**Comment by Daniel-Mietchen** [comment]
Just tried out the ldf client together with @maxlath, and here's how it works:

```
ldf-client https://query.wikidata.org/bigdata/ldf query.sparql 
```

with query.sparql containing

```SPARQL
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?item ?pmid WHERE {
  ?item wdt:P698 ?pmid .
}
LIMIT 100

```

**Comment by Daniel-Mietchen** [comment]
This results in the following output:

```
[
{"?item":"http://www.wikidata.org/entity/Q39162663","?pmid":"\"19920\""},
{"?item":"http://www.wikidata.org/entity/Q39963305","?pmid":"\"172585\""},
{"?item":"http://www.wikidata.org/entity/Q39067544","?pmid":"\"1208\""},
{"?item":"http://www.wikidata.org/entity/Q39682052","?pmid":"\"113076\""},
{"?item":"http://www.wikidata.org/entity/Q39888322","?pmid":"\"156842\""},
{"?item":"http://www.wikidata.org/entity/Q39689439","?pmid":"\"114686\""},
{"?item":"http://www.wikidata.org/entity/Q39676900","?pmid":"\"111968\""},
{"?item":"http://www.wikidata.org/entity/Q43416222","?pmid":"\"1000111\""},
{"?item":"http://www.wikidata.org/entity/Q45260896","?pmid":"\"10575180\""},
{"?item":"http://www.wikidata.org/entity/Q39908422","?pmid":"\"161170\""},
{"?item":"http://www.wikidata.org/entity/Q35896459","?pmid":"\"14000228\""},
{"?item":"http://www.wikidata.org/entity/Q39647933","?pmid":"\"105612\""},
{"?item":"http://www.wikidata.org/entity/Q39067510","?pmid":"\"1201\""},
{"?item":"http://www.wikidata.org/entity/Q46692417","?pmid":"\"1779775\""},
{"?item":"http://www.wikidata.org/entity/Q39646122","?pmid":"\"105244\""},
{"?item":"http://www.wikidata.org/entity/Q39942652","?pmid":"\"168080\""},
{"?item":"http://www.wikidata.org/entity/Q36090621","?pmid":"\"183803\""},
{"?item":"http://www.wikidata.org/entity/Q39812460","?pmid":"\"140290\""},
{"?item":"http://www.wikidata.org/entity/Q35372340","?pmid":"\"13954\""},
{"?item":"http://www.wikidata.org/entity/Q30104757","?pmid":"\"17\""},
{"?item":"http://www.wikidata.org/entity/Q33785719","?pmid":"\"105835\""},
{"?item":"http://www.wikidata.org/entity/Q39632950","?pmid":"\"102376\""},
{"?item":"http://www.wikidata.org/entity/Q39067530","?pmid":"\"1205\""},
{"?item":"http://www.wikidata.org/entity/Q39784996","?pmid":"\"134923\""},
{"?item":"http://www.wikidata.org/entity/Q39633789","?pmid":"\"102550\""},
{"?item":"http://www.wikidata.org/entity/Q39063412","?pmid":"\"157\""},
{"?item":"http://www.wikidata.org/entity/Q36003453","?pmid":"\"156393\""},
{"?item":"http://www.wikidata.org/entity/Q39683797","?pmid":"\"113452\""},
{"?item":"http://www.wikidata.org/entity/Q39657275","?pmid":"\"107557\""},
{"?item":"http://www.wikidata.org/entity/Q39953529","?pmid":"\"170444\""},
{"?item":"http://www.wikidata.org/entity/Q39063479","?pmid":"\"171\""},
{"?item":"http://www.wikidata.org/entity/Q39901478","?pmid":"\"159696\""},
{"?item":"http://www.wikidata.org/entity/Q39657439","?pmid":"\"107596\""},
{"?item":"http://www.wikidata.org/entity/Q39929817","?pmid":"\"165475\""},
{"?item":"http://www.wikidata.org/entity/Q30110837","?pmid":"\"122\""},
{"?item":"http://www.wikidata.org/entity/Q39664820","?pmid":"\"109223\""},
{"?item":"http://www.wikidata.org/entity/Q39121306","?pmid":"\"11000\""},
{"?item":"http://www.wikidata.org/entity/Q50629281","?pmid":"\"1211738\""},
{"?item":"http://www.wikidata.org/entity/Q39645887","?pmid":"\"105195\""},
{"?item":"http://www.wikidata.org/entity/Q39067668","?pmid":"\"1240\""},
{"?item":"http://www.wikidata.org/entity/Q30110872","?pmid":"\"100\""},
{"?item":"http://www.wikidata.org/entity/Q39977314","?pmid":"\"175710\""},
{"?item":"http://www.wikidata.org/entity/Q39063537","?pmid":"\"186\""},
{"?item":"http://www.wikidata.org/entity/Q52239276","?pmid":"\"1702419\""},
{"?item":"http://www.wikidata.org/entity/Q28300472","?pmid":"\"19\""},
{"?item":"http://www.wikidata.org/entity/Q39987533","?pmid":"\"178100\""},
{"?item":"http://www.wikidata.org/entity/Q44465307","?pmid":"\"1506933\""},
{"?item":"http://www.wikidata.org/entity/Q39067621","?pmid":"\"1227\""},
{"?item":"http://www.wikidata.org/entity/Q33331239","?pmid":"\"10640847\""},
{"?item":"http://www.wikidata.org/entity/Q41015499","?pmid":"\"1260637\""},
{"?item":"http://www.wikidata.org/entity/Q39067521","?pmid":"\"1203\""},
{"?item":"http://www.wikidata.org/entity/Q39847540","?pmid":"\"147312\""},
{"?item":"http://www.wikidata.org/entity/Q39067534","?pmid":"\"1206\""},
{"?item":"http://www.wikidata.org/entity/Q39067547","?pmid":"\"1209\""},
{"?item":"http://www.wikidata.org/entity/Q46521210","?pmid":"\"10645083\""},
{"?item":"http://www.wikidata.org/entity/Q39149719","?pmid":"\"17242\""},
{"?item":"http://www.wikidata.org/entity/Q39063457","?pmid":"\"166\""},
{"?item":"http://www.wikidata.org/entity/Q39126469","?pmid":"\"12026\""},
{"?item":"http://www.wikidata.org/entity/Q42086459","?pmid":"\"1000078\""},
{"?item":"http://www.wikidata.org/entity/Q28216999","?pmid":"\"12\""},
{"?item":"http://www.wikidata.org/entity/Q39646360","?pmid":"\"105295\""},
{"?item":"http://www.wikidata.org/entity/Q40019482","?pmid":"\"184999\""},
{"?item":"http://www.wikidata.org/entity/Q30104762","?pmid":"\"11\""},
{"?item":"http://www.wikidata.org/entity/Q39063408","?pmid":"\"156\""},
{"?item":"http://www.wikidata.org/entity/Q39644945","?pmid":"\"104990\""},
{"?item":"http://www.wikidata.org/entity/Q39643275","?pmid":"\"104611\""},
{"?item":"http://www.wikidata.org/entity/Q28340889","?pmid":"\"1204623\""},
{"?item":"http://www.wikidata.org/entity/Q39624803","?pmid":"\"100686\""},
{"?item":"http://www.wikidata.org/entity/Q48340259","?pmid":"\"147471\""},
{"?item":"http://www.wikidata.org/entity/Q39131105","?pmid":"\"12970\""},
{"?item":"http://www.wikidata.org/entity/Q39645957","?pmid":"\"105209\""},
{"?item":"http://www.wikidata.org/entity/Q39912091","?pmid":"\"161950\""},
{"?item":"http://www.wikidata.org/entity/Q39067540","?pmid":"\"1207\""},
{"?item":"http://www.wikidata.org/entity/Q39657749","?pmid":"\"107664\""},
{"?item":"http://www.wikidata.org/entity/Q39067525","?pmid":"\"1204\""},
{"?item":"http://www.wikidata.org/entity/Q27905658","?pmid":"\"1\""},
{"?item":"http://www.wikidata.org/entity/Q39645132","?pmid":"\"105032\""},
{"?item":"http://www.wikidata.org/entity/Q30110868","?pmid":"\"112\""},
{"?item":"http://www.wikidata.org/entity/Q39128318","?pmid":"\"12419\""},
{"?item":"http://www.wikidata.org/entity/Q39644916","?pmid":"\"104984\""},
{"?item":"http://www.wikidata.org/entity/Q34515552","?pmid":"\"14658\""},
{"?item":"http://www.wikidata.org/entity/Q38357972","?pmid":"\"105720\""},
{"?item":"http://www.wikidata.org/entity/Q30104759","?pmid":"\"10\""},
{"?item":"http://www.wikidata.org/entity/Q39752781","?pmid":"\"128204\""},
{"?item":"http://www.wikidata.org/entity/Q51160163","?pmid":"\"1902718\""},
{"?item":"http://www.wikidata.org/entity/Q39067504","?pmid":"\"1200\""},
{"?item":"http://www.wikidata.org/entity/Q39069466","?pmid":"\"1674\""},
{"?item":"http://www.wikidata.org/entity/Q39937936","?pmid":"\"167069\""},
{"?item":"http://www.wikidata.org/entity/Q39870128","?pmid":"\"152980\""},
{"?item":"http://www.wikidata.org/entity/Q33536306","?pmid":"\"10037033\""},
{"?item":"http://www.wikidata.org/entity/Q39063496","?pmid":"\"176\""},
{"?item":"http://www.wikidata.org/entity/Q39146041","?pmid":"\"16274\""},
{"?item":"http://www.wikidata.org/entity/Q39144820","?pmid":"\"15951\""},
{"?item":"http://www.wikidata.org/entity/Q42450137","?pmid":"\"1289170\""},
{"?item":"http://www.wikidata.org/entity/Q39125375","?pmid":"\"11816\""},
{"?item":"http://www.wikidata.org/entity/Q39977309","?pmid":"\"175709\""},
{"?item":"http://www.wikidata.org/entity/Q37043272","?pmid":"\"1814991\""},
{"?item":"http://www.wikidata.org/entity/Q39912832","?pmid":"\"162115\""},
{"?item":"http://www.wikidata.org/entity/Q31440494","?pmid":"\"11000000\""},
{"?item":"http://www.wikidata.org/entity/Q39805871","?pmid":"\"139062\""}
]

```

**Comment by maxlath** [comment]
reporting from `ldf-client` tests:
```sparql
# hamburg_painting.rq
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT ?item ?image
WHERE
{
  ?item wdt:P31/wdt:P279* wd:Q3305213 .
  ?item wdt:P180 ?object .
  ?item ?prop ?hhlink .
  ?hhlink ?prop2 wd:Q1055 .
  ?object wdt:P279* wd:Q34379 .
  ?item wdt:P18 ?image .
}
```
```sh
$ ldf-client https://query.wikidata.org/bigdata/ldf hamburg_painting.rq
```
output:
```
[[Fri May 18 2018 22:08:27 GMT+0200 (CEST)] WARNING TriplePatternIterator Could not retrieve https://query.wikidata.org/bigdata/ldf?subject=http%3A%2F%2Fwww.wikidata.org%2Fentity%2Fstatement%2FQ17275832-06ecc90d-4ff0-d81c-146f-62025c4c85cf&object=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ1055 (429)
ERROR: An error occurred during query execution.

Error: Could not retrieve https://query.wikidata.org/bigdata/ldf?subject=http%3A%2F%2Fwww.wikidata.org%2Fentity%2Fstatement%2FQ17275832-06ecc90d-4ff0-d81c-146f-62025c4c85cf&object=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ1055 (429)
    at Immediate.<anonymous> (/home/maxlath/.nvm/versions/node/v8.2.1/lib/node_modules/ldf-client/lib/triple-pattern-fragments/FragmentsClient.js:133:29)
    at runCallback (timers.js:783:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
[Fri May 18 2018 22:08:28 GMT+0200 (CEST)] WARNING TriplePatternIterator Could not retrieve https://query.wikidata.org/bigdata/ldf?subject=http%3A%2F%2Fwww.wikidata.org%2Fentity%2Fstatement%2FQ17275832-9b078834-4e8f-b69c-5f21-186bda26270b&object=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ1055 (429)
ERROR: An error occurred during query execution.

Error: Could not retrieve https://query.wikidata.org/bigdata/ldf?subject=http%3A%2F%2Fwww.wikidata.org%2Fentity%2Fstatement%2FQ17275832-9b078834-4e8f-b69c-5f21-186bda26270b&object=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ1055 (429)
    at Immediate.<anonymous> (/home/maxlath/.nvm/versions/node/v8.2.1/lib/node_modules/ldf-client/lib/triple-pattern-fragments/FragmentsClient.js:133:29)
    at runCallback (timers.js:783:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
[Fri May 18 2018 22:08:30 GMT+0200 (CEST)] WARNING TriplePatternIterator Could not retrieve https://query.wikidata.org/bigdata/ldf?subject=http%3A%2F%2Fwww.wikidata.org%2Fentity%2Fstatement%2FQ29469377-193FC580-FD52-4188-87E1-F2CB54117CF6&object=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ1055 (429)
ERROR: An error occurred during query execution.

Error: Could not retrieve https://query.wikidata.org/bigdata/ldf?subject=http%3A%2F%2Fwww.wikidata.org%2Fentity%2Fstatement%2FQ29469377-193FC580-FD52-4188-87E1-F2CB54117CF6&object=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ1055 (429)
    at Immediate.<anonymous> (/home/maxlath/.nvm/versions/node/v8.2.1/lib/node_modules/ldf-client/lib/triple-pattern-fragments/FragmentsClient.js:133:29)
    at runCallback (timers.js:783:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
[Fri May 18 2018 22:08:35 GMT+0200 (CEST)] WARNING TriplePatternIterator Could not retrieve https://query.wikidata.org/bigdata/ldf?object=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ34379&page=13 (429)
ERROR: An error occurred during query execution.

Error: Could not retrieve https://query.wikidata.org/bigdata/ldf?object=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ34379&page=13 (429)
    at Immediate.<anonymous> (/home/maxlath/.nvm/versions/node/v8.2.1/lib/node_modules/ldf-client/lib/triple-pattern-fragments/FragmentsClient.js:133:29)
    at runCallback (timers.js:783:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
]
```
